--------------------------------------------------------
--  Constraints for Table G_COTS_LTR_REQ_TB
--------------------------------------------------------

  ALTER TABLE "ets_dev"."G_COTS_LTR_REQ_TB" ADD ;
  ALTER TABLE "ets_dev"."G_COTS_LTR_REQ_TB" ADD ;
  ALTER TABLE "ets_dev"."G_COTS_LTR_REQ_TB" ADD ;
  ALTER TABLE "ets_dev"."G_COTS_LTR_REQ_TB" ADD ;
  ALTER TABLE "ets_dev"."G_COTS_LTR_REQ_TB" ADD ;
  ALTER TABLE "ets_dev"."G_COTS_LTR_REQ_TB" MODIFY ("G_COTS_LTR_REQ_SK" NOT NULL );
  ALTER TABLE "ets_dev"."G_COTS_LTR_REQ_TB" MODIFY ("G_COTS_LTR_TMPLT_KEY_DATA" NOT NULL );
  ALTER TABLE "ets_dev"."G_COTS_LTR_REQ_TB" MODIFY ("G_SPRVSR_REVW_REQD_IND" NOT NULL );
  ALTER TABLE "ets_dev"."G_COTS_LTR_REQ_TB" MODIFY ("G_USER_ID" NOT NULL );
  ALTER TABLE "ets_dev"."G_COTS_LTR_REQ_TB" MODIFY ("G_COTS_LTR_REQ_DISP_CD" NOT NULL );
  ALTER TABLE "ets_dev"."G_COTS_LTR_REQ_TB" ADD CONSTRAINT "G_COTS_LTR_REQ_PK" PRIMARY KEY ("G_COTS_LTR_REQ_SK") ;
  ALTER TABLE "ets_dev"."G_COTS_LTR_REQ_TB" MODIFY ("L_HIBERNATE_VER_NUM" NOT NULL );
  ALTER TABLE "ets_dev"."G_COTS_LTR_REQ_TB" MODIFY ("G_AUD_USER_ID" NOT NULL );
  ALTER TABLE "ets_dev"."G_COTS_LTR_REQ_TB" MODIFY ("G_AUD_TS" NOT NULL );
  ALTER TABLE "ets_dev"."G_COTS_LTR_REQ_TB" MODIFY ("G_AUD_ADD_USER_ID" NOT NULL );
  ALTER TABLE "ets_dev"."G_COTS_LTR_REQ_TB" MODIFY ("G_AUD_ADD_TS" NOT NULL );
