--------------------------------------------------------
--  Ref Constraints for Table G_COTS_LTR_REQ_TB
--------------------------------------------------------

  ALTER TABLE "ets_dev"."G_COTS_LTR_REQ_TB" ADD CONSTRAINT "G_COTS_LTR_REQ_F4" FOREIGN KEY ("G_ALERT_BASED_ON_TABLE_NAM", "G_ALERT_BASED_ON_COL_NAM")
	  REFERENCES "ets_dev"."R_DD_COL_TB" ("R_TABLE_NAM", "R_COL_NAM") ;
  ALTER TABLE "ets_dev"."G_COTS_LTR_REQ_TB" ADD CONSTRAINT "G_COTS_LTR_REQ_F3" FOREIGN KEY ("G_NOTFY_ALERT_USER_ID")
	  REFERENCES "ets_dev"."G_USER_TB" ("G_USER_ID") ;
  ALTER TABLE "ets_dev"."G_COTS_LTR_REQ_TB" ADD CONSTRAINT "G_COTS_LTR_REQ_F1" FOREIGN KEY ("G_COTS_LTR_TMPLT_KEY_DATA")
	  REFERENCES "ets_dev"."G_COTS_LTR_TMPLT_TB" ("G_COTS_LTR_TMPLT_KEY_DATA") ;
  ALTER TABLE "ets_dev"."G_COTS_LTR_REQ_TB" ADD CONSTRAINT "G_COTS_LTR_REQ_F5" FOREIGN KEY ("G_NOTE_SET_SK", "G_NOTE_SEQ_NUM")
	  REFERENCES "ets_dev"."G_NOTE_TB" ("G_NOTE_SET_SK", "G_NOTE_SEQ_NUM") ;
  ALTER TABLE "ets_dev"."G_COTS_LTR_REQ_TB" ADD CONSTRAINT "G_COTS_LTR_REQ_F2" FOREIGN KEY ("G_USER_ID")
	  REFERENCES "ets_dev"."G_USER_TB" ("G_USER_ID") ;
