--------------------------------------------------------
--  Constraints for Table G_COTS_LTR_REQ_RECR_TB
--------------------------------------------------------

  ALTER TABLE "ets_dev"."G_COTS_LTR_REQ_RECR_TB" MODIFY ("G_COTS_LTR_REQ_RECR_SK" NOT NULL );
  ALTER TABLE "ets_dev"."G_COTS_LTR_REQ_RECR_TB" MODIFY ("G_COTS_LTR_REQ_SK" NOT NULL );
  ALTER TABLE "ets_dev"."G_COTS_LTR_REQ_RECR_TB" MODIFY ("G_LTR_REQ_COMMUN_MTHD_CD" NOT NULL );
  ALTER TABLE "ets_dev"."G_COTS_LTR_REQ_RECR_TB" MODIFY ("L_HIBERNATE_VER_NUM" NOT NULL );
  ALTER TABLE "ets_dev"."G_COTS_LTR_REQ_RECR_TB" MODIFY ("G_AUD_USER_ID" NOT NULL );
  ALTER TABLE "ets_dev"."G_COTS_LTR_REQ_RECR_TB" MODIFY ("G_AUD_TS" NOT NULL );
  ALTER TABLE "ets_dev"."G_COTS_LTR_REQ_RECR_TB" MODIFY ("G_AUD_ADD_USER_ID" NOT NULL );
  ALTER TABLE "ets_dev"."G_COTS_LTR_REQ_RECR_TB" MODIFY ("G_AUD_ADD_TS" NOT NULL );
  ALTER TABLE "ets_dev"."G_COTS_LTR_REQ_RECR_TB" ADD ;
  ALTER TABLE "ets_dev"."G_COTS_LTR_REQ_RECR_TB" ADD CONSTRAINT "G_COTS_LTR_REQ_RECR_PK" PRIMARY KEY ("G_COTS_LTR_REQ_RECR_SK") ;
  ALTER TABLE "ets_dev"."G_COTS_LTR_REQ_RECR_TB" ADD ;
  ALTER TABLE "ets_dev"."G_COTS_LTR_REQ_RECR_TB" ADD ;
  ALTER TABLE "ets_dev"."G_COTS_LTR_REQ_RECR_TB" ADD ;
  ALTER TABLE "ets_dev"."G_COTS_LTR_REQ_RECR_TB" ADD ;
