--------------------------------------------------------
--  Constraints for Table G_PYE_PYR_EFT_SETUP_TB
--------------------------------------------------------

  ALTER TABLE "ets_dev"."G_PYE_PYR_EFT_SETUP_TB" MODIFY ("G_CMN_ENTY_SK" NOT NULL );
  ALTER TABLE "ets_dev"."G_PYE_PYR_EFT_SETUP_TB" MODIFY ("G_PYE_PYR_EFT_SETUP_SEQ_NUM" NOT NULL );
  ALTER TABLE "ets_dev"."G_PYE_PYR_EFT_SETUP_TB" MODIFY ("G_EFT_SETUP_BEG_DT" NOT NULL );
  ALTER TABLE "ets_dev"."G_PYE_PYR_EFT_SETUP_TB" MODIFY ("G_EFT_SETUP_END_DT" NOT NULL );
  ALTER TABLE "ets_dev"."G_PYE_PYR_EFT_SETUP_TB" MODIFY ("G_BIN_ROUTNG_NUM" NOT NULL );
  ALTER TABLE "ets_dev"."G_PYE_PYR_EFT_SETUP_TB" MODIFY ("L_HIBERNATE_VER_NUM" NOT NULL );
  ALTER TABLE "ets_dev"."G_PYE_PYR_EFT_SETUP_TB" MODIFY ("G_AUD_USER_ID" NOT NULL );
  ALTER TABLE "ets_dev"."G_PYE_PYR_EFT_SETUP_TB" MODIFY ("G_AUD_TS" NOT NULL );
  ALTER TABLE "ets_dev"."G_PYE_PYR_EFT_SETUP_TB" MODIFY ("G_AUD_ADD_USER_ID" NOT NULL );
  ALTER TABLE "ets_dev"."G_PYE_PYR_EFT_SETUP_TB" MODIFY ("G_AUD_ADD_TS" NOT NULL );
  ALTER TABLE "ets_dev"."G_PYE_PYR_EFT_SETUP_TB" ADD ;
  ALTER TABLE "ets_dev"."G_PYE_PYR_EFT_SETUP_TB" ADD CONSTRAINT "G_PYE_PYR_EFT_SETUP_PK" PRIMARY KEY ("G_CMN_ENTY_SK", "G_PYE_PYR_EFT_SETUP_SEQ_NUM") ;
  ALTER TABLE "ets_dev"."G_PYE_PYR_EFT_SETUP_TB" ADD ;
  ALTER TABLE "ets_dev"."G_PYE_PYR_EFT_SETUP_TB" ADD ;
  ALTER TABLE "ets_dev"."G_PYE_PYR_EFT_SETUP_TB" ADD ;
  ALTER TABLE "ets_dev"."G_PYE_PYR_EFT_SETUP_TB" ADD ;
