--------------------------------------------------------
--  DDL for Table G_PYE_PYR_EFT_SETUP_TB
--------------------------------------------------------

  CREATE TABLE "ets_dev"."G_PYE_PYR_EFT_SETUP_TB"
   (	"G_CMN_ENTY_SK" BIGINT,
	"G_PYE_PYR_EFT_SETUP_SEQ_NUM" INTEGER,
	"G_EFT_SETUP_BEG_DT" TIMESTAMP,
	"G_EFT_SETUP_END_DT" TIMESTAMP,
	"G_BIN_ROUTNG_NUM" VARCHAR(12),
	"G_FIN_INST_NAM" VARCHAR(50),
	"G_EFT_STAT_CD" VARCHAR(2),
	"G_EFT_STAT_DT" TIMESTAMP,
	"G_EFT_ACCT_TY_CD" VARCHAR(2),
	"G_EFT_ACCT_NUM" VARCHAR(15),
	"G_BANK_BRNCH_NAM" VARCHAR(50),
	"G_PRE_NOTE_DT" TIMESTAMP,
	"G_ACCT_HLDR_NAM" VARCHAR(50),
	"G_PROV_PYE_NAM" VARCHAR(50),
	"G_BANK_ADR_SK" BIGINT,
	"G_BANK_PHONE_SK" BIGINT,
	"L_HIBERNATE_VER_NUM" INTEGER DEFAULT 0,
	"G_AUD_USER_ID" VARCHAR(30),
	"G_AUD_TS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"G_AUD_ADD_USER_ID" VARCHAR(30),
	"G_AUD_ADD_TS" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"G_EFT_ACCT_NUM_LNKG_DESC" VARCHAR(50),
	"G_EFT_SUBM_RSN_DESC" VARCHAR(18),
	"G_EFT_AUTH_SIGN_DESC" VARCHAR(50),
	"G_EFT_STREET_ADR" VARCHAR(64),
	"G_PROV_ADR_SK" BIGINT
   );
