--------------------------------------------------------
--  Constraints for Table R_PARAM_DTL_TB
--------------------------------------------------------

  ALTER TABLE "ets_dev"."R_PARAM_DTL_TB" MODIFY ("R_FUNC_AREA_CD" NOT NULL );
  ALTER TABLE "ets_dev"."R_PARAM_DTL_TB" MODIFY ("R_PARAM_NUM" NOT NULL );
  ALTER TABLE "ets_dev"."R_PARAM_DTL_TB" MODIFY ("R_PARAM_DTL_SK" NOT NULL );
  ALTER TABLE "ets_dev"."R_PARAM_DTL_TB" MODIFY ("R_LOB_CD" NOT NULL );
  ALTER TABLE "ets_dev"."R_PARAM_DTL_TB" MODIFY ("R_PARAM_BEG_DT" NOT NULL );
  ALTER TABLE "ets_dev"."R_PARAM_DTL_TB" MODIFY ("R_PARAM_END_DT" NOT NULL );
  ALTER TABLE "ets_dev"."R_PARAM_DTL_TB" MODIFY ("L_HIBERNATE_VER_NUM" NOT NULL );
  ALTER TABLE "ets_dev"."R_PARAM_DTL_TB" MODIFY ("G_AUD_USER_ID" NOT NULL );
  ALTER TABLE "ets_dev"."R_PARAM_DTL_TB" MODIFY ("G_AUD_TS" NOT NULL );
  ALTER TABLE "ets_dev"."R_PARAM_DTL_TB" MODIFY ("G_AUD_ADD_USER_ID" NOT NULL );
  ALTER TABLE "ets_dev"."R_PARAM_DTL_TB" MODIFY ("G_AUD_ADD_TS" NOT NULL );
  ALTER TABLE "ets_dev"."R_PARAM_DTL_TB" ADD CONSTRAINT "R_PARAM_DTL_UX1" UNIQUE ("R_FUNC_AREA_CD", "R_PARAM_NUM", "R_LOB_CD", "R_PARAM_BEG_DT", "R_VOID_DT") ;
  ALTER TABLE "ets_dev"."R_PARAM_DTL_TB" ADD ;
  ALTER TABLE "ets_dev"."R_PARAM_DTL_TB" ADD ;
  ALTER TABLE "ets_dev"."R_PARAM_DTL_TB" ADD ;
  ALTER TABLE "ets_dev"."R_PARAM_DTL_TB" ADD ;
  ALTER TABLE "ets_dev"."R_PARAM_DTL_TB" ADD CONSTRAINT "R_PARAM_DTL_PK" PRIMARY KEY ("R_FUNC_AREA_CD", "R_PARAM_NUM", "R_PARAM_DTL_SK") ;
  ALTER TABLE "ets_dev"."R_PARAM_DTL_TB" ADD ;
